spring.application.name=vicheth_sokhsedtha

server.port=8091

# MySQL Datasource
spring.datasource.url=jdbc:mysql://mysql:3306/B-Vicheth_Sokhsedtha-db
spring.datasource.username=root
spring.datasource.password=Hello@123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Photo upload
photo.upload-dir=uploads/photos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false